### PR TITLE
[CITE-159] - Fetching all authorities the user has access to for the …

### PR DESCRIPTION
**Pull request by MaulikLim**
…'all' option

# Guidelines for Pull Requests

If you haven't yet read our code review guidelines, please do so, You can find them [here](https://diging.atlassian.net/wiki/spaces/DIGING/pages/2256076801/Code+Review+Guidelines).

Please confirm the following by adding an x for each item (turn `[ ]` into `[x]`).

- [x] I have removed all code style changes that are not necessary (e.g. changing blanks across the whole file that don’t need to be changed, adding empty lines in parts other than your own code)
- [x] I am not making any changes to files that don’t have any effect (e.g. imports added that don’t need to be added)
- [x] I do not have any sysout statements in my code or commented out code that isn’t needed anymore
- [x] I am not reformatting any files in the wrong format or without cause. 
- [x] I am not changing file encoding or line endings to something else than UTF-8, LF
- [x] My pull request does not show an insane amount of files being changed although my ticket only requires a few files being changed
- [x] I have added Javadoc/documentation where appropriate
- [x] I have added test cases where appropriate
- [x] I have explained any part of my code/implementation decisions that is not be self-explanatory

## Please provide a brief description of your ticket 
(you can copy the ticket if it hasn't changed) 

[CITE-159] - Managed authorities: for groups, it needs to show all authorities of that group
  
## Anything else the reviewer needs to know?

... describe here ...

[CITE-159]: https://diging.atlassian.net/browse/CITE-159?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by tjquinn1** [comment]
Jenkins, make it so.

**Comment by tjquinn1** [comment]
Jenkins, Make it so.

**Comment by tjquinn1** [comment]
Make it so, Jenkins.

**Comment by jdamerow** [comment]
Make it so, Jenkins.

**Comment by jdamerow** [comment]
There is a compilation error. My guess is the model version isn't right?
```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.1:compile (default-compile) on project citesphere: Compilation failure
[ERROR] /var/lib/jenkins/workspace/citesphere_deploy_to_review_on_pr/citesphere/src/main/java/edu/asu/diging/citesphere/core/service/impl/AuthorityService.java:[291,31] cannot find symbol
[ERROR] symbol:   method findByUsernameOrGroupsInOrderByName(java.lang.String,java.util.List<java.lang.Long>)
[ERROR] location: variable entryRepository of type edu.asu.diging.citesphere.data.AuthorityEntryRepository
```

**Comment by jdamerow** [comment]
Make it so, Jenkins.

**Pull request merged**
